[package]
name = "wn"
version = "0.1.0"
authors = ["Utkarsh Kukreti <utkarshkukreti@gmail.com>"]
edition = "2018"

[dependencies]
quick-xml = { version = "0.22", features = ["serialize"] }
serde = { version = "1", features = ["derive"] }
thiserror = "1"
