name: Main

on: [push, pull_request]

jobs:
  main:
    name: ${{ matrix.os }} - ${{ matrix.rust }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        rust: [stable, nightly, 1.53.0]
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          override: true
          components: clippy, rustfmt
      - run: make
      - run: cargo build --release
      - run: cargo test --release
      - run: cargo fmt -- --check
      - run: cargo clippy
